server:
  port: 8082

spring:
  datasource:
    url: jdbc:mariadb://gangbean-stock-service-rdb.cplifuxv1ysv.ap-northeast-2.rds.amazonaws.com:3306/stock_service
    driver-class-name: org.mariadb.jdbc.Driver
    username: xbox2537
    password: xbox2537

  jpa:
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: false

logging:
  level:
    sql: debug
    org.hibernate.type: INFO

jwt:
  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret'|base64
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  access-token-validity-in-seconds: 7_200
  refresh-token-validity-in-seconds: 1_209_600